<?php

declare(strict_types=1);

namespace Cybersalt\Plugin\System\Csmcpforjpagebuilderckfree\Tools\Content;

\defined('_JEXEC') or die;

use Cybersalt\Component\Csmcpforj\Administrator\MCP\AbstractTool;
use Cybersalt\Component\Csmcpforj\Administrator\MCP\ToolResult;
use Cybersalt\Plugin\System\Csmcpforjpagebuilderckfree\Tools\PagebuilderckBootTrait;
use Cybersalt\Plugin\System\Csmcpforjpagebuilderckfree\Tools\PagebuilderckContentTrait;
use Joomla\CMS\User\User;

/**
 * Everything about one block: its type, its options, its markup and its CSS.
 *
 * ---------------------------------------------------------------------------
 * WHAT A BLOCK ACTUALLY IS
 * ---------------------------------------------------------------------------
 *
 *   <div id="ID1706635981585" class="cktype" data-type="audio">
 *     <div class="tab_audio ckprops" audiourl="images/x.mp3" fieldslist="…"></div>
 *     <div class="ckstyle"><style>#ID1706635981585 { … }</style></div>
 *     <div class="inner">…the visible payload…</div>
 *   </div>
 *
 * There is no JSON anywhere. A block's options are HTML ATTRIBUTES on the empty
 * `.ckprops` sibling divs, one div per tab of the vendor's options popup. The
 * conventions are unusual enough that reading them wrong is easy, which is why
 * this tool parses them for you rather than handing back raw markup.
 *
 * The `.ckstyle` CSS is generated by the editor, not by the renderer —
 * `administrator/helpers/stylescss.php` is included only by the admin views and
 * the editor's AJAX endpoints. What is stored in that div is the only CSS the
 * front end ever sees for this block.
 */
final class GetBlockTool extends AbstractTool
{
	use PagebuilderckBootTrait;
	use PagebuilderckContentTrait;
	use PageContentEditTrait;

	public function getName(): string { return 'get_pagebuilderck_block'; }

	public function getDescription(): string
	{
		return 'Return one block of a Page Builder CK page in full: its data-type, its parsed options, '
			. 'its inner markup and its #id-scoped .ckstyle CSS. Get block ids from '
			. 'get_pagebuilderck_page_outline. '
			. 'OPTIONS ARE HTML ATTRIBUTES, NOT JSON. Each block carries one empty '
			. '<div class="tab_x ckprops"> per tab of the vendor\'s options popup, and every option is '
			. 'an attribute on that div. Four conventions matter and all four are easy to get wrong: '
			. '(1) the attribute NAME is the ID of the input in the options popup, not its name — radios '
			. 'share a name but have distinct ids, which is why you see iconalignementleft, '
			. 'iconalignementcenter and iconalignementright as three separate attributes rather than one '
			. 'alignment value; (2) checkbox and radio values are the LITERAL STRING "checked", never '
			. '"1", "true" or "yes"; (3) the value "default" means unset, and so does an empty string — '
			. 'the vendor removes such attributes entirely rather than storing them, so ABSENCE is the '
			. 'only representation of "no value"; (4) the fieldslist attribute is a comma-separated index '
			. 'of which attributes the options popup considers set. It is rebuilt from the live popup on '
			. 'every editor save while the attributes are written separately, so the two legitimately '
			. 'disagree in real data. Both are reported here rather than reconciled, along with '
			. 'declared_but_absent and set_but_undeclared where they differ. '
			. 'Also returns the block\'s .ckstyle CSS. That CSS is generated by the EDITOR, not at render '
			. 'time, so it will not follow a change made to the options by '
			. 'update_pagebuilderck_block — see that tool\'s warnings. '
			. 'Read-only. Arguments: page_id, block_id.';
	}

	public function getInputSchema(): array
	{
		return [
			'type' => 'object',
			'properties' => [
				'page_id'  => ['type' => 'integer', 'description' => 'Row id in #__pagebuilderck_pages.'],
				'id'       => ['type' => 'integer', 'description' => 'Alias for page_id.'],
				'block_id' => ['type' => 'string', 'description' => 'The id attribute of the .cktype div, e.g. ID1706635981585. From get_pagebuilderck_page_outline.'],
			],
			'required'             => ['block_id'],
			'additionalProperties' => false,
		];
	}

	public function getRequiredPermission(): string { return 'read'; }

	protected function run(array $arguments, User $actor): ToolResult
	{
		if (($guard = $this->pbckContentGuard()) !== null) {
			return $guard;
		}

		$pageId  = $this->pbckPageId($arguments);
		$blockId = $this->requireString($arguments, 'block_id');
		$row     = $this->pbckLoadPageRow($pageId);

		if ($row === null) {
			return $this->pbckPageNotFoundError($pageId);
		}

		$html = (string) $row['htmlcode'];
		$dom  = $this->pbckParse($html);

		if ($dom === null) {
			return ToolResult::json([
				'ok'    => false,
				'error' => 'The content of page ' . $pageId . ' could not be parsed. Run '
					. 'validate_pagebuilderck_content on it.',
				'component' => $this->pbckEditionNotice(),
			], true);
		}

		$block = $this->pbckFindBlock($dom, $blockId);

		if ($block === null) {
			$knownBlocks  = $this->pbckBlockIds($dom);
			$knownColumns = $this->pbckColumnIds($dom);
			$dom->clear();

			return ToolResult::json([
				'ok'    => false,
				'error' => 'No block with id "' . $blockId . '" on page ' . $pageId . '.',
				'hint'  => \in_array($blockId, $knownColumns, true)
					? 'That id belongs to a COLUMN (div.blockck), not a block (div.cktype). Confusingly, '
						. 'Page Builder CK calls its columns "blockck" and its blocks "cktype". Columns hold '
						. 'blocks; pass a block id here, or use that id as column_id in '
						. 'add_pagebuilderck_block.'
					: 'Run get_pagebuilderck_page_outline for the ids that exist on this page.',
				'block_ids_on_page' => $knownBlocks,
				'component' => $this->pbckEditionNotice(),
			], true);
		}

		$type    = (string) $block->getAttribute('data-type');
		$enabled = $this->pbckEnabledAddonTypes();
		$props   = $this->pbckReadProps($block);

		$result = [
			'ok'       => true,
			'page'     => $this->pbckPageSummary($row),
			'block_id' => $blockId,
			'type'     => $type,
		];

		$column = $this->pbckNearestAncestorWithClass($block, 'blockck');

		if ($column !== null) {
			$result['column_id'] = (string) $column->getAttribute('id');
		}

		// --- addon status ----------------------------------------------------
		if ($type === '') {
			$result['type_error'] = 'This block has no data-type at all. Page Builder CK renders a literal '
				. 'red "ELEMENT TYPE NOT FOUND" paragraph into the page for it.';
		} elseif (\in_array($type, $this->pbckCoreTypes(), true)) {
			$result['addon'] = ['status' => 'core', 'note' => 'Handled by the component itself, with no plugin.'];
		} elseif (\in_array($type, $enabled, true)) {
			$result['addon'] = ['status' => 'enabled'];
		} else {
			$result['addon'] = [
				'status'  => 'missing',
				'warning' => 'No enabled pagebuilderck plugin provides type "' . $type . '". Page Builder '
					. 'CK does NOT blank this block — it renders the inner markup below as static HTML '
					. 'with the .ckstyle CSS still applied, with no error and no log entry. The page looks '
					. 'nearly right; the addon\'s interactive behaviour is gone. Editing inner_html here '
					. 'is still meaningful, because that static markup IS what visitors see.',
			];
		}

		// --- options ---------------------------------------------------------
		$result['options'] = $props;
		$result['options_note'] = 'Attribute names are the ids of inputs in the vendor\'s options popup. '
			. 'Checkbox and radio values are the literal string "checked". "default" and "" both mean '
			. 'unset, so an option you cannot see here simply has no value. Pass changes back to '
			. 'update_pagebuilderck_block as {"tab_blocstyles": {"blocpaddings": "20"}}.';

		if ($props === []) {
			$result['options_note'] = 'This block has no .ckprops divs at all, so it carries no options. '
				. 'That is normal for a block added outside the builder, and for the simplest addons.';
		}

		// --- ckstyle ---------------------------------------------------------
		$styleNode = $this->pbckDirectChild($block, 'ckstyle');

		if ($styleNode === null) {
			$result['ckstyle'] = [
				'present' => false,
				'note'    => 'This block has no .ckstyle div, so it has no block-scoped CSS and the editor '
					. 'has nowhere to write any. Page Builder CK\'s own addons always emit one, even '
					. 'empty.',
			];
		} else {
			$css = (string) $styleNode->innertext;

			$result['ckstyle'] = [
				'present' => true,
				'bytes'   => \strlen($css),
				'css'     => $this->pbckExpandRoot($css),
				'note'    => 'Every rule here is scoped to #' . $blockId . '. It is written by the EDITOR '
					. '(administrator/helpers/stylescss.php, which the site renderer never includes), so '
					. 'it does not track changes made to the options by any tool — it only changes when a '
					. 'human opens this block in the builder and applies.',
			];
		}

		// --- inner payload ---------------------------------------------------
		$inner = $this->pbckDirectChild($block, 'inner');

		if ($inner !== null) {
			$innerHtml = (string) $inner->innertext;

			$result['inner'] = [
				'wrapper_present' => true,
				'wrapper_class'   => (string) $inner->getAttribute('class'),
				'bytes'           => \strlen($innerHtml),
				'html'            => $this->pbckExpandRoot($innerHtml),
			];
		} else {
			// Not every addon wraps its payload. The shipped `icon` addon, for one,
			// emits <div class="iconck"> directly as a sibling of .ckstyle.
			$parts = [];

			foreach ($block->children() as $child) {
				if ($this->pbckNodeHasClass($child, 'ckprops') || $this->pbckNodeHasClass($child, 'ckstyle')) {
					continue;
				}

				$parts[] = (string) $child->outertext();
			}

			$innerHtml = implode('', $parts);

			$result['inner'] = [
				'wrapper_present' => false,
				'bytes'           => \strlen($innerHtml),
				'html'            => $this->pbckExpandRoot($innerHtml),
				'note'            => 'This block has NO div.inner wrapper — the markup above is everything '
					. 'that is not a .ckprops or .ckstyle child. Several shipped addons are built this way '
					. '(the icon addon emits div.iconck directly). update_pagebuilderck_block cannot set '
					. 'inner_html on a block with no .inner wrapper and will refuse rather than guess; use '
					. 'write_pagebuilderck_page_content for those.',
			];
		}

		// --- ACL -------------------------------------------------------------
		$acl = trim((string) $block->getAttribute('data-acl-view'));

		if ($acl !== '') {
			$result['acl_view'] = [
				'denied_group_ids' => array_values(array_filter(array_map('trim', explode(',', $acl)))),
				'note' => 'data-acl-view reads like an allow list. It is a DENY list — the group ids here '
					. 'are the ones that CANNOT see this block.',
			];
		}

		$result['outer_bytes'] = \strlen((string) $block->outertext());

		$dom->clear();

		$result['component'] = $this->pbckEditionNotice();

		return ToolResult::json($result);
	}
}
